# Generated by Django 4.1.4 on 2023-01-04 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_price', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('staff_password', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=20)),
                ('vendor_address', models.CharField(max_length=100)),
                ('vendor_contact', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_description',
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='item_quantity',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('product_price', models.FloatField(default=None)),
                ('total_price', models.FloatField(default=None)),
                ('valid_until', models.DateField()),
                ('quantity_provided', models.PositiveIntegerField()),
                ('quotation_status', models.CharField(max_length=20)),
                ('product_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('staff_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
                ('vendor_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=40)),
                ('quantity_provided', models.PositiveIntegerField()),
                ('item_price', models.FloatField(default=None)),
                ('total_price', models.FloatField(default=None)),
                ('quantity_needed', models.PositiveIntegerField()),
                ('po_status', models.CharField(max_length=20)),
                ('item_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('quotation_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.quotation')),
                ('staff_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
                ('vendor_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
    ]
