# Generated by Django 4.1.4 on 2023-01-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_staff_vendor_remove_item_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
