# Generated by Django 4.1.4 on 2023-01-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='item_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='product_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
