# Generated by Django 4.1.4 on 2023-01-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_item_item_price_alter_product_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_quantity',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
