# Generated by Django 4.1.4 on 2023-01-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_item_item_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quantity_provided',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_password',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
