# Generated by Django 4.1.4 on 2023-01-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_item_price_alter_product_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='test_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
