# Generated by Django 4.1.4 on 2023-01-18 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vendor_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('productID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=40, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('productPriceperUnit', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('qtyProvided', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('itemID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=40, null=True)),
                ('quantity', models.PositiveIntegerField(default=None, null=True)),
                ('itemPriceperUnit', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('qtyNeeded', models.PositiveIntegerField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor_id',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='po_status',
            new_name='poStatus',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='po_id',
            new_name='purchaseOrderID',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='quantity_needed',
            new_name='qtyNeeded',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='quantity_provided',
            new_name='qtyProvided',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='quotation_id',
            new_name='quotationID',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='staff_id',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='item_price',
            new_name='totalPrice',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='vendor_id',
            new_name='vendorID',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='quantity_provided',
            new_name='qtyProvided',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='quotation_id',
            new_name='quotationID',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='quotation_status',
            new_name='quotationStatus',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='staff_id',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='product_price',
            new_name='totalPrice',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='valid_until',
            new_name='validityDate',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='vendor_id',
            new_name='vendorID',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_id',
            new_name='staffID',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_address',
            new_name='vendorAddress',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_contact',
            new_name='vendorContact',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_id',
            new_name='vendorID',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='test_name',
            new_name='vendorName',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_name',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='vendorID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='vendorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='productID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.purchaseorderproduct'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='itemID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.quotationitem'),
        ),
    ]
